# Valuation techniques
- In this file, examples of valuation techniques with real values will be implemented. 

In [2]:
import numpy as np

## NPV - Classic 
- Net present value as a sum of discounted cash flow with constant discount rate. 

In [3]:
interest_rate = 0.1
cash_flows = np.insert(np.repeat(100,14),0,-1000)
cash_flows

array([-1000,   100,   100,   100,   100,   100,   100,   100,   100,
         100,   100,   100,   100,   100,   100])

In [4]:
def get_NPV_classic(cash_flows, interest_rate): 
    current_discount = 1
    NPV = 0
    
    for v in cash_flows:
        current_value = v/current_discount
        NPV = NPV + current_value
        current_discount = current_discount*(1+interest_rate)
        
    return(NPV)
        

In [5]:
get_NPV(cash_flows, 0.10)

-263.3312543060804

## NPV - variable interest rate
- Now the interest rate is variable but still expected to be known. 


In [26]:
def get_NPV_variable_IR(cash_flows, interest_rates): 
    if(len(cash_flows)!=len(interest_rates)): 
        Exception("The length of cash flow vector is different from the length of the interest rate vector...")
    
    current_discount = 1
    NPV = 0
    
    for i in range(len(cash_flows)):
        print(interest_rates[i])
        print(cash_flows[i])
        print(NPV)
        current_value = cash_flows[i]/current_discount
        NPV = NPV + current_value
        current_discount = current_discount*(1+interest_rates[i])
        
    return(NPV)

In [29]:
interest_rates = np.linspace(0.1,0.058,15)
display(interest_rates)
cash_flows = np.insert(np.repeat(100,14),0,-1000)
cash_flows

array([0.1  , 0.097, 0.094, 0.091, 0.088, 0.085, 0.082, 0.079, 0.076,
       0.073, 0.07 , 0.067, 0.064, 0.061, 0.058])

array([-1000,   100,   100,   100,   100,   100,   100,   100,   100,
         100,   100,   100,   100,   100,   100])

In [30]:
get_NPV_variable_IR(cash_flows,interest_rates)

0.1
-1000
0
0.097
100
-1000.0
0.094
100
-909.0909090909091
0.091
100
-826.2202701582829
0.08800000000000001
100
-750.470143163195
0.085
100
-681.0383127368999
0.082
100
-617.2222921244963
0.079
100
-558.4056832651382
0.07600000000000001
100
-504.0465253544561
0.07300000000000001
100
-453.66732432509355
0.07
100
-406.8465055245708
0.067
100
-363.2110732780444
0.064
100
-322.4302954775525
0.061000000000000006
100
-284.2102600506622
0.058
100
-248.28917412313376


-214.43329671735762